name: targetedfileconverter
description: Converts empirical libraries to different formats
keywords:
  - OpenMS
  - DIA
  - Library
tools:
  - ProteinInference:
      description: |
        Converts empirical libraries to different formats
      homepage: TODO
      documentation: TODO
input:
  - empirical_library_in:
      type: file
      description: |
        An empirical library in .tsv format.
      pattern: "*.tsv"
output:
  - empirical_library_out:
      type: file
      description: |
        An empirical library in .pqp format.
      pattern: "*.pqp"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@jcharkow"
